### ISSUE TITLE
bower and/or npm

### ISSUE THREAD

**Issue by alinnert** [vickramravichandran/angular-auto-complete#1]
After a very long search I found this auto-complete directive to be the best. It works and is nice to work with.
But I'm a little surprised that you can't find it on [bower](http://bower.io/) or [npm](https://www.npmjs.com/). Can you add it there please? It makes things a lot easier.
Thanks.

**Comment by vickramravichandran** [comment]
Good to know you liked the plugin. I have added it to both npm and bower. Let me know how it goes.

`npm install angular-auto-complete`
`bower install angular-auto-complete`

I did not list `angular` and `angular-sanitize` as dependencies. Even if I add them as dependencies, you still need to manually include them on the page.

Thanks.

**Comment by alinnert** [comment]
Perfect. Thanks a lot.

That about `angular` and `angular-sanitize` is fine. I've included them already.
