### ISSUE TITLE
Please mention steps how to make is runable.

### ISSUE THREAD

**Issue by yasir-rafiq** [vickramravichandran/angular-auto-complete#10]
Need ti include CSS, JSS, module dependency?

**Comment by vickramravichandran** [comment]
Please see this Gist

https://gist.github.com/vickramravichandran/0a09056ec818885191e504a398ade71a

...and working sample:

https://codepen.io/vickramravichandran/pen/bYMGPd

**Comment by vickramravichandran** [comment]
Let me know if you still have questions about setting it up.
