### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by yehhor** [vickramravichandran/angular-auto-complete#12]
Hi there!
First of all, I would like you to know that you have developed a great lib, thank you!

But I have some problem with it. During npm install script it throws an error 

> node - v8.1.2
> npm - 5.0.3
> npm ERR! path /angular/node_modules/angular-auto-complete
> npm ERR! code EISGIT
> npm ERR! git /angular/node_modules/angular-auto-complete: Appears to be a git repo or submodule.
> npm ERR! git     /angular/node_modules/angular-auto-complete
> npm ERR! git Refusing to remove it. Update manually,
> npm ERR! git or move it out of the way first.
> npm ERR! A complete log of this run can be found in:
> npm ERR!    /.npm/_logs/2017-12-05T11_31_01_062Z-debug.log

I am using last version of your lib and tried some versions before.

I found the same issue in another library, and it seems to be library issue, could you clarify please?
https://github.com/shama/napa/issues/53

Thank you!

**Comment by vickramravichandran** [comment]
Are you using napa?

**Comment by yehhor** [comment]
package.json

**Comment by yehhor** [comment]
Also if i delete .git folder from node_modules/angular-auto-complete - problem disappears

**Comment by vickramravichandran** [comment]
Delete the `.git` folder inside the `node_modules\angular-auto-complete` folder and try `npm install` again.

I don't understand where `npm install` gets it from. There is no such directory in the master branch https://github.com/vickramravichandran/angular-auto-complete

Moreover, npmjs [documentation](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) says '.git' directory is automatically ignored.

**Comment by vickramravichandran** [comment]
Something is not right. The `package.json` file in `node_modules\angular-auto-complete` has `"version": "1.5.0"` instead of `1.5.1`

I will bump the version to `1.5.2` and publish to npm again.

**Comment by vickramravichandran** [comment]
I published 1.5.3 to npm as seen on their website https://www.npmjs.com/package/angular-auto-complete. 
However, `npm i angular-auto-complete` installs `1.5.2` instead of `1.5.3`. I think it will take a while to update.

**Comment by vickramravichandran** [comment]
I decided to publish `1.5.4` when the npm registry did not pick up `1.5.3`. It worked this time. The `dist-tags` in npm registry points to `1.5.4` https://registry.npmjs.org/angular-auto-complete

```javascript
"dist-tags": {
  "latest": "1.5.4"
},
```

**Comment by yehhor** [comment]
it works! thanks.
