### ISSUE TITLE
keyword search method

### ISSUE THREAD

**Issue by DeokHee** [vickramravichandran/angular-auto-complete#15]
Hi
angular-auto-complete module is awesome 

i want to talk about keyword search method

you used startWith function to find target keyword

but it isn't enough to search something

i recommend you using includes function

have a nice day 

============ code =============

vm.autoCompleteOptions = {
          minimumChars: 2,
          dropdownWidth: '400px',
          containerCssClass: 'color-codes',
          selectedTextAttr: 'name',
          data: function (searchText) {
              searchText = searchText.toUpperCase();
              return _.filter(data, function (data) {
                  return  **data.name.includes(searchText);**
              });
          },
          itemSelected: function (item) {
            
          }
};

**Comment by vickramravichandran** [comment]
Done..

<img src="https://user-images.githubusercontent.com/2133516/37568700-6a5b8078-2aaf-11e8-9d1f-9de118ae1d4e.png" width="250">
