### ISSUE TITLE
Please provide The "No Result Match" message when no matches are found in list

### ISSUE THREAD

**Issue by sureshreddynareddy** [vickramravichandran/angular-auto-complete#18]
Please add a message if no results match for  when we search the list.
like the below image 
![screenshot from 2018-03-09 16-19-50](https://user-images.githubusercontent.com/17561519/37204123-e6168880-23b5-11e8-885f-78f6a06b4440.png)

**Comment by vickramravichandran** [comment]
I published a new version 1.7.0 with this feature. It can be configured using the following options:

`noMatchTemplateEnabled`: _Set to true to enable the template to display a message when no items match the search text._ Default `true`
`noMatchTemplateEnabled`: _The template used to display the message when no items match the search text. Default `<span>No results match '{{entry.searchText}}'></span>`"_

<img src="https://user-images.githubusercontent.com/2133516/37568493-225b010c-2aac-11e8-8124-f6e243deb6c7.png" width="150">
