### ISSUE TITLE
Please provide access to ng-repeat current object access.

### ISSUE THREAD

**Issue by vigneswaranp** [vickramravichandran/angular-auto-complete#19]
In my scenario I keep the auto-complete input in ng-repeat after selecting from the list i want to include other properties of the object to ng-repeat specific object.
Example: ng-repeat=" flower in flower"
<input ng-model="flower.color" auto-complete="options">

selectItem=function(e){ 
/*Here i need to have flower object access so that i will assign other values without affecting original. */
 var item =e.item;
 flower.name = item.name;
 flower.country =  item.country;
}
Something like this.

**Comment by vickramravichandran** [comment]
This should work...

```html
<div ng-repeat="flower in ctrl.flowers">
  <p>
     <input ng-model="selectedFlower"
            type="text"
            auto-complete="ctrl.getAutoCompleteConfig(flower)" />
  </p>     
</div>
```

```javascript

// Inside the controller
var self = $scope.ctrl = this;
self.flowers = getFlowers();

// get the flower as a function parameter
this.getAutoCompleteConfig = function(flower) {
  return {
     /* other config options omitted for brevity */
     itemSelected: function(e) {
       var item = e.item;
       // now you have access to the flower object
       flower.name = item.name;
       flower.country = item.country;
      }
   }
};
```

**Comment by vigneswaranp** [comment]
Thank u.. It works fine for me

**Comment by vigneswaranp** [comment]
Please include this example in document.
