### ISSUE TITLE
Dropdown dont close on unfocus

### ISSUE THREAD

**Issue by cosmosdesigner** [vickramravichandran/angular-auto-complete#20]
Hi Vickram, first of all, nice work, keep going :)
Soooo, my issue is in IE11, the dropdown doesnt close at first attempt, i have to click twice outside to close the dropdown;
Chrome, FF, Safari all fine.

Thx and nice work.

**Comment by vickramravichandran** [comment]
I am not seeing that behavior on the [demo site](http://demo.vickram.me/angular-auto-complete/) when using IE11. Clicking outside once does hide the dropdown.

**Comment by cosmosdesigner** [comment]
Weird... The dropdown only close when click outside twice.

I already tested again now.

I will debug and try to plunk to you.

Thx



A quarta, 4/04/2018, 20:33, Vickram Ravichandran <notifications@github.com>
escreveu:

**Comment by vickramravichandran** [comment]
Here is a gif of the dropdown hiding on click

![angular-auto-complete-ie11](https://user-images.githubusercontent.com/2133516/38336631-73e08718-3830-11e8-8c43-a2392d93c43b.gif)
