### ISSUE TITLE
CSS | Dropdown position

### ISSUE THREAD

**Issue by aviadhahami** [vickramravichandran/angular-auto-complete#3]
> **TL;DR** - dropdown shows at the bottom left of the screen

Hey!
I'm trying to use your library in my project, and I've encountered a CSS problem.
For some reason, the dropdown shows in the bottom left of the screen, rather than where the input field is located.
I'm using the directive inside a component, can that be an issue?

**Comment by vickramravichandran** [comment]
Did you solve this issue? I was not able to reproduce this behavior. I think it might have something to do with the position property of the textbox. What browser are you using? Is it possible to reproduce the behavior in jsfiddle or codepen?

**Comment by aviadhahami** [comment]
I didn't solved it, used another solution (product managers had to compromise ;) 
The textbox (`input type="text"`) was given the bootstrap `form-controller` class. nothing fancy.
I can give it a shot in few days. Kinda loaded with work stuff tho

**Comment by vickramravichandran** [comment]
Just curious. Are you using `jquery.ui`? If yes, try commenting the `if` statement block at line 444 that uses jquery ui's `position()`

https://github.com/vickramravichandran/angular-auto-complete/blob/master/angular-auto-complete.js#L444

**Comment by vickramravichandran** [comment]
I have published a new version. Please try again. I have added two new options: 

- `positionUsingJQuery`: If true will position the dropdown list using the position() method from the jQueryUI library. See https://api.jqueryui.com/position/
- `positionUsing`: Options that will be passed to jQueryUI position() method

**Comment by aviadhahami** [comment]
Will try

**Comment by craiggoldstone** [comment]
We don't use jQuery UI in our project and I was able to solve this using:

``` positionUsingJQuery: false ```

Would be useful to update the docs to say that's what you need if not using jQuery UI... or even better, update the project to remove that pseudo-dependency and make the position work by default for all!
