### ISSUE TITLE
Wont work on iOS Chrome/Safari

### ISSUE THREAD

**Issue by pytlakow** [vickramravichandran/angular-auto-complete#6]
Hi 
I implemented the plugin but it seems not to work with onscreen keyboard on mobile devices. 
Is this known issue? Something not correct with screen keyboard events detection?
Kris

**Comment by vickramravichandran** [comment]
I never tested this on iOS. However, this works on Android Chrome browser.

**Comment by vickramravichandran** [comment]
I made some changes to make it work with iOS (see attached images). Please try it out and let me know. http://vickramravichandran.github.io/angular-auto-complete/

<table>
<tr>
<td>
<img src='https://cloud.githubusercontent.com/assets/2133516/26114280/d7bb272a-3a2a-11e7-85fd-46acf7f7730b.jpg' height='600'>
</td>
<td>
<img src='https://cloud.githubusercontent.com/assets/2133516/26114341/0581a47c-3a2b-11e7-8571-44d1157ff1ad.jpg' height='600'>
</td>
</tr>
</table>

**Comment by vickramravichandran** [comment]
I have published a new version. Please try it out.
